print(" GGG " + "  " + " SSS ")
print("G   G" + "  " + "S   S")
print("G    " + "  " + "S    ")
print("GGGGG" + "  " + " SSS ")
print("G   G" + "  " + "    S")
print("G   G" + "  " + "S   S")
print(" GGG " + "  " + " SSS ")
